# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc.__python_out import chat_pb2 as grpc_dot_____python__out_dot_chat__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc/__python_out/chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatStub(object):
    """Simple RPCs where client sends a request to the server
    using stub and waits for a response to come back
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/Chat/SendMessage',
                request_serializer=grpc_dot_____python__out_dot_chat__pb2.GeneralMessage.SerializeToString,
                response_deserializer=grpc_dot_____python__out_dot_chat__pb2.Response.FromString,
                _registered_method=True)
        self.SendUsername = channel.unary_unary(
                '/Chat/SendUsername',
                request_serializer=grpc_dot_____python__out_dot_chat__pb2.Username.SerializeToString,
                response_deserializer=grpc_dot_____python__out_dot_chat__pb2.Response.FromString,
                _registered_method=True)
        self.SendPassword = channel.unary_unary(
                '/Chat/SendPassword',
                request_serializer=grpc_dot_____python__out_dot_chat__pb2.Password.SerializeToString,
                response_deserializer=grpc_dot_____python__out_dot_chat__pb2.Response.FromString,
                _registered_method=True)


class ChatServicer(object):
    """Simple RPCs where client sends a request to the server
    using stub and waits for a response to come back
    """

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=grpc_dot_____python__out_dot_chat__pb2.GeneralMessage.FromString,
                    response_serializer=grpc_dot_____python__out_dot_chat__pb2.Response.SerializeToString,
            ),
            'SendUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.SendUsername,
                    request_deserializer=grpc_dot_____python__out_dot_chat__pb2.Username.FromString,
                    response_serializer=grpc_dot_____python__out_dot_chat__pb2.Response.SerializeToString,
            ),
            'SendPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPassword,
                    request_deserializer=grpc_dot_____python__out_dot_chat__pb2.Password.FromString,
                    response_serializer=grpc_dot_____python__out_dot_chat__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Chat', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Chat(object):
    """Simple RPCs where client sends a request to the server
    using stub and waits for a response to come back
    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Chat/SendMessage',
            grpc_dot_____python__out_dot_chat__pb2.GeneralMessage.SerializeToString,
            grpc_dot_____python__out_dot_chat__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Chat/SendUsername',
            grpc_dot_____python__out_dot_chat__pb2.Username.SerializeToString,
            grpc_dot_____python__out_dot_chat__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Chat/SendPassword',
            grpc_dot_____python__out_dot_chat__pb2.Password.SerializeToString,
            grpc_dot_____python__out_dot_chat__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
